function [ labels ] = doCCBCutCluster( img, k )
%DOCCBCUTCLUSTER 此处显示有关此函数的摘要
%   此处显示详细说明
optsCCNCut = ccbcutSet('Display','iter',...
    'Algorithm','irrq',...
    'Tau',1,...
    'BalanceType','normalized',...
    'RoundingType','kmeans',...
    'KmeansNumStartPoints',1,...
    'MinIRRQIters',5,...
    'MaxIRRQIters',50,...
    'TolIRRQX',eps,...
    'TolIRRQF',eps,...
    'TolIRRQL1',1e-5,...
    'TolIRRQL1Curv',0.08,...
    'Epsilon',1,...
    'KRatio',0.0001,...
    'IRRQConstraint','hard');


sigma = 50;
img = im2double(img);

[X, Y, Z] = size(img);
N = X * Y;
imgVals = reshape(img,N,Z); clear Lab;
[~, edges] = lattice(X,Y,1);
weights = makeweights_old(edges,imgVals,sigma);
W = adjacency(edges,weights,N); clear edges weights;

W = (W + W') / 2;

[~, d] = myccbcut(W, k, [], optsCCNCut);

idx = kmeans(d, k ,'Distance', 'sqeuclidean', 'Replicates', 20, 'MaxIter', 5000, 'Options',statset('UseParallel',1));

labels = reshape(idx, [X, Y]);

end

